// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

const pooledUrl = process.env.DATABASE_URL;

const withPgBouncerSafeParams = (url: string): string => {
  const parsed = new URL(url);
  parsed.searchParams.set("pgbouncer", "true");
  parsed.searchParams.set("statement_cache_size", "0");
  return parsed.toString();
};

const migrationBaseUrl = process.env.DATABASE_URL ?? process.env.MIGRATION_DATABASE_URL;
const migrationUrl = migrationBaseUrl
  ? withPgBouncerSafeParams(migrationBaseUrl)
  : undefined;

if (!migrationUrl) {
  throw new Error(
    "Set DATABASE_URL (or MIGRATION_DATABASE_URL) before running Prisma commands."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate/db push/introspect) uses this URL.
    // We enforce PgBouncer-safe flags for pooler-based Supabase connections.
    url: migrationUrl,
  },
});
